package oracle.apps.ak.tickets.server;

import oracle.apps.ak.tickets.schema.trainEOImpl;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class trainVORowImpl extends OAViewRowImpl {
    public static final int IDNUM = 0;
    public static final int TRAINNAME = 1;
    public static final int TIMEONEPLACE = 2;
    public static final int ONEPLACE = 3;
    public static final int PRICESECONDOFONEPART = 4;
    public static final int PRICEFIRSTOFONEPART = 5;
    public static final int PRICEBUSINESSOFONEPART = 6;
    public static final int TIMETWOPLACE = 7;
    public static final int TWOPLACE = 8;
    public static final int PRICESECONDOFTWOPART = 9;
    public static final int PRICEFIRSTOFTWOPART = 10;
    public static final int PRICEBUSINESSOFTWOPART = 11;
    public static final int TIMETHREEPLACE = 12;
    public static final int THREEPLACE = 13;
    public static final int PRICESECONDOFTHREEPART = 14;
    public static final int PRICEFIRSTOFTHREEPART = 15;
    public static final int PRICEBUSINESSOFTHREEPART = 16;
    public static final int TIMEFOREPLACE = 17;
    public static final int FOREPLACE = 18;
    public static final int PRICESECONDOFFOREPART = 19;
    public static final int PRICEFIRSTOFFOREPART = 20;
    public static final int PRICEBUSINESSOFFOREPART = 21;
    public static final int TIMEFIVEPLACE = 22;
    public static final int FIVEPLACE = 23;
    public static final int PRICESECONDOFFIVEPART = 24;
    public static final int PRICEFIRSTOFFIVEPART = 25;
    public static final int PRICEBUSINESSOFFIVEPART = 26;
    public static final int TIMESIXPLACE = 27;
    public static final int SIXPLACE = 28;
    public static final int ONESECONDCLASSSEAT = 29;
    public static final int TWOSECONDCLASSSEAT = 30;
    public static final int THREESECONDCLASSSEAT = 31;
    public static final int FORESECONDCLASSSEAT = 32;
    public static final int FIVESECONDCLASSSEAT = 33;
    public static final int ONEFIRSTCLASSSEAT = 34;
    public static final int TWOFIRSTCLASSSEAT = 35;
    public static final int THREEFIRSTCLASSSEAT = 36;
    public static final int FOREFIRSTCLASSSEAT = 37;
    public static final int FIVEFIRSTCLASSSEAT = 38;
    public static final int ONEBUSINESSCLASSSEAT = 39;
    public static final int TWOBUSINESSCLASSSEAT = 40;
    public static final int THREEBUSINESSCLASSSEAT = 41;
    public static final int FOREBUSINESSCLASSSEAT = 42;
    public static final int FIVEBUSINESSCLASSSEAT = 43;
    public static final int NUMBERCOLUMN = 44;
    public static final int LASTUPDATEDATE = 45;
    public static final int LASTUPDATEDBY = 46;
    public static final int CREATIONDATE = 47;
    public static final int CREATEDBY = 48;
    public static final int LASTUPDATELOGIN = 49;
    public static final int YMD = 50;
    public static final int STARTPLACE = 51;
    public static final int DESTINATIONPLACE = 52;
    public static final int STARTTIME = 53;
    public static final int ENDTIME = 54;
    public static final int ALLTIME = 55;
    public static final int PRICE = 56;
    public static final int SORTSEAT = 57;
    public static final int PRICETHREE = 58;
    public static final int COUNTSEAT = 59;
    public static final int NAMECUSTOMER = 60;
    public static final int IDCUSTOMER = 61;
    public static final int IDNUMCHANGE = 62;
    public static final int IDTRAINCHANGE = 63;
    public static final int STARTSTATIONCHANGE = 64;
    public static final int ENDSTATIONCHANGE = 65;
    public static final int SEATCLASSCHANGE = 66;

    /**This is the default constructor (do not remove)
     */
    public trainVORowImpl() {
    }

    /**Gets trainEO entity object.
     */
    public trainEOImpl gettrainEO() {
        return (trainEOImpl)getEntity(0);
    }

    /**Gets the attribute value for IDNUM using the alias name Idnum
     */
    public Number getIdnum() {
        return (Number) getAttributeInternal(IDNUM);
    }

    /**Sets <code>value</code> as attribute value for IDNUM using the alias name Idnum
     */
    public void setIdnum(Number value) {
        setAttributeInternal(IDNUM, value);
    }

    /**Gets the attribute value for TRAINNAME using the alias name Trainname
     */
    public String getTrainname() {
        return (String) getAttributeInternal(TRAINNAME);
    }

    /**Sets <code>value</code> as attribute value for TRAINNAME using the alias name Trainname
     */
    public void setTrainname(String value) {
        setAttributeInternal(TRAINNAME, value);
    }

    /**Gets the attribute value for TIMEONEPLACE using the alias name Timeoneplace
     */
    public Date getTimeoneplace() {
        return (Date) getAttributeInternal(TIMEONEPLACE);
    }

    /**Sets <code>value</code> as attribute value for TIMEONEPLACE using the alias name Timeoneplace
     */
    public void setTimeoneplace(Date value) {
        setAttributeInternal(TIMEONEPLACE, value);
    }

    /**Gets the attribute value for ONEPLACE using the alias name Oneplace
     */
    public String getOneplace() {
        return (String) getAttributeInternal(ONEPLACE);
    }

    /**Sets <code>value</code> as attribute value for ONEPLACE using the alias name Oneplace
     */
    public void setOneplace(String value) {
        setAttributeInternal(ONEPLACE, value);
    }

    /**Gets the attribute value for PRICESECONDOFONEPART using the alias name Pricesecondofonepart
     */
    public Number getPricesecondofonepart() {
        return (Number) getAttributeInternal(PRICESECONDOFONEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICESECONDOFONEPART using the alias name Pricesecondofonepart
     */
    public void setPricesecondofonepart(Number value) {
        setAttributeInternal(PRICESECONDOFONEPART, value);
    }

    /**Gets the attribute value for PRICEFIRSTOFONEPART using the alias name Pricefirstofonepart
     */
    public Number getPricefirstofonepart() {
        return (Number) getAttributeInternal(PRICEFIRSTOFONEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEFIRSTOFONEPART using the alias name Pricefirstofonepart
     */
    public void setPricefirstofonepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFONEPART, value);
    }

    /**Gets the attribute value for PRICEBUSINESSOFONEPART using the alias name Pricebusinessofonepart
     */
    public Number getPricebusinessofonepart() {
        return (Number) getAttributeInternal(PRICEBUSINESSOFONEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEBUSINESSOFONEPART using the alias name Pricebusinessofonepart
     */
    public void setPricebusinessofonepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFONEPART, value);
    }

    /**Gets the attribute value for TIMETWOPLACE using the alias name Timetwoplace
     */
    public Date getTimetwoplace() {
        return (Date) getAttributeInternal(TIMETWOPLACE);
    }

    /**Sets <code>value</code> as attribute value for TIMETWOPLACE using the alias name Timetwoplace
     */
    public void setTimetwoplace(Date value) {
        setAttributeInternal(TIMETWOPLACE, value);
    }

    /**Gets the attribute value for TWOPLACE using the alias name Twoplace
     */
    public String getTwoplace() {
        return (String) getAttributeInternal(TWOPLACE);
    }

    /**Sets <code>value</code> as attribute value for TWOPLACE using the alias name Twoplace
     */
    public void setTwoplace(String value) {
        setAttributeInternal(TWOPLACE, value);
    }

    /**Gets the attribute value for PRICESECONDOFTWOPART using the alias name Pricesecondoftwopart
     */
    public Number getPricesecondoftwopart() {
        return (Number) getAttributeInternal(PRICESECONDOFTWOPART);
    }

    /**Sets <code>value</code> as attribute value for PRICESECONDOFTWOPART using the alias name Pricesecondoftwopart
     */
    public void setPricesecondoftwopart(Number value) {
        setAttributeInternal(PRICESECONDOFTWOPART, value);
    }

    /**Gets the attribute value for PRICEFIRSTOFTWOPART using the alias name Pricefirstoftwopart
     */
    public Number getPricefirstoftwopart() {
        return (Number) getAttributeInternal(PRICEFIRSTOFTWOPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEFIRSTOFTWOPART using the alias name Pricefirstoftwopart
     */
    public void setPricefirstoftwopart(Number value) {
        setAttributeInternal(PRICEFIRSTOFTWOPART, value);
    }

    /**Gets the attribute value for PRICEBUSINESSOFTWOPART using the alias name Pricebusinessoftwopart
     */
    public Number getPricebusinessoftwopart() {
        return (Number) getAttributeInternal(PRICEBUSINESSOFTWOPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEBUSINESSOFTWOPART using the alias name Pricebusinessoftwopart
     */
    public void setPricebusinessoftwopart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFTWOPART, value);
    }

    /**Gets the attribute value for TIMETHREEPLACE using the alias name Timethreeplace
     */
    public Date getTimethreeplace() {
        return (Date) getAttributeInternal(TIMETHREEPLACE);
    }

    /**Sets <code>value</code> as attribute value for TIMETHREEPLACE using the alias name Timethreeplace
     */
    public void setTimethreeplace(Date value) {
        setAttributeInternal(TIMETHREEPLACE, value);
    }

    /**Gets the attribute value for THREEPLACE using the alias name Threeplace
     */
    public String getThreeplace() {
        return (String) getAttributeInternal(THREEPLACE);
    }

    /**Sets <code>value</code> as attribute value for THREEPLACE using the alias name Threeplace
     */
    public void setThreeplace(String value) {
        setAttributeInternal(THREEPLACE, value);
    }

    /**Gets the attribute value for PRICESECONDOFTHREEPART using the alias name Pricesecondofthreepart
     */
    public Number getPricesecondofthreepart() {
        return (Number) getAttributeInternal(PRICESECONDOFTHREEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICESECONDOFTHREEPART using the alias name Pricesecondofthreepart
     */
    public void setPricesecondofthreepart(Number value) {
        setAttributeInternal(PRICESECONDOFTHREEPART, value);
    }

    /**Gets the attribute value for PRICEFIRSTOFTHREEPART using the alias name Pricefirstofthreepart
     */
    public Number getPricefirstofthreepart() {
        return (Number) getAttributeInternal(PRICEFIRSTOFTHREEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEFIRSTOFTHREEPART using the alias name Pricefirstofthreepart
     */
    public void setPricefirstofthreepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFTHREEPART, value);
    }

    /**Gets the attribute value for PRICEBUSINESSOFTHREEPART using the alias name Pricebusinessofthreepart
     */
    public Number getPricebusinessofthreepart() {
        return (Number) getAttributeInternal(PRICEBUSINESSOFTHREEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEBUSINESSOFTHREEPART using the alias name Pricebusinessofthreepart
     */
    public void setPricebusinessofthreepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFTHREEPART, value);
    }

    /**Gets the attribute value for TIMEFOREPLACE using the alias name Timeforeplace
     */
    public Date getTimeforeplace() {
        return (Date) getAttributeInternal(TIMEFOREPLACE);
    }

    /**Sets <code>value</code> as attribute value for TIMEFOREPLACE using the alias name Timeforeplace
     */
    public void setTimeforeplace(Date value) {
        setAttributeInternal(TIMEFOREPLACE, value);
    }

    /**Gets the attribute value for FOREPLACE using the alias name Foreplace
     */
    public String getForeplace() {
        return (String) getAttributeInternal(FOREPLACE);
    }

    /**Sets <code>value</code> as attribute value for FOREPLACE using the alias name Foreplace
     */
    public void setForeplace(String value) {
        setAttributeInternal(FOREPLACE, value);
    }

    /**Gets the attribute value for PRICESECONDOFFOREPART using the alias name Pricesecondofforepart
     */
    public Number getPricesecondofforepart() {
        return (Number) getAttributeInternal(PRICESECONDOFFOREPART);
    }

    /**Sets <code>value</code> as attribute value for PRICESECONDOFFOREPART using the alias name Pricesecondofforepart
     */
    public void setPricesecondofforepart(Number value) {
        setAttributeInternal(PRICESECONDOFFOREPART, value);
    }

    /**Gets the attribute value for PRICEFIRSTOFFOREPART using the alias name Pricefirstofforepart
     */
    public Number getPricefirstofforepart() {
        return (Number) getAttributeInternal(PRICEFIRSTOFFOREPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEFIRSTOFFOREPART using the alias name Pricefirstofforepart
     */
    public void setPricefirstofforepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFFOREPART, value);
    }

    /**Gets the attribute value for PRICEBUSINESSOFFOREPART using the alias name Pricebusinessofforepart
     */
    public Number getPricebusinessofforepart() {
        return (Number) getAttributeInternal(PRICEBUSINESSOFFOREPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEBUSINESSOFFOREPART using the alias name Pricebusinessofforepart
     */
    public void setPricebusinessofforepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFFOREPART, value);
    }

    /**Gets the attribute value for TIMEFIVEPLACE using the alias name Timefiveplace
     */
    public Date getTimefiveplace() {
        return (Date) getAttributeInternal(TIMEFIVEPLACE);
    }

    /**Sets <code>value</code> as attribute value for TIMEFIVEPLACE using the alias name Timefiveplace
     */
    public void setTimefiveplace(Date value) {
        setAttributeInternal(TIMEFIVEPLACE, value);
    }

    /**Gets the attribute value for FIVEPLACE using the alias name Fiveplace
     */
    public String getFiveplace() {
        return (String) getAttributeInternal(FIVEPLACE);
    }

    /**Sets <code>value</code> as attribute value for FIVEPLACE using the alias name Fiveplace
     */
    public void setFiveplace(String value) {
        setAttributeInternal(FIVEPLACE, value);
    }

    /**Gets the attribute value for PRICESECONDOFFIVEPART using the alias name Pricesecondoffivepart
     */
    public Number getPricesecondoffivepart() {
        return (Number) getAttributeInternal(PRICESECONDOFFIVEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICESECONDOFFIVEPART using the alias name Pricesecondoffivepart
     */
    public void setPricesecondoffivepart(Number value) {
        setAttributeInternal(PRICESECONDOFFIVEPART, value);
    }

    /**Gets the attribute value for PRICEFIRSTOFFIVEPART using the alias name Pricefirstoffivepart
     */
    public Number getPricefirstoffivepart() {
        return (Number) getAttributeInternal(PRICEFIRSTOFFIVEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEFIRSTOFFIVEPART using the alias name Pricefirstoffivepart
     */
    public void setPricefirstoffivepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFFIVEPART, value);
    }

    /**Gets the attribute value for PRICEBUSINESSOFFIVEPART using the alias name Pricebusinessoffivepart
     */
    public Number getPricebusinessoffivepart() {
        return (Number) getAttributeInternal(PRICEBUSINESSOFFIVEPART);
    }

    /**Sets <code>value</code> as attribute value for PRICEBUSINESSOFFIVEPART using the alias name Pricebusinessoffivepart
     */
    public void setPricebusinessoffivepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFFIVEPART, value);
    }

    /**Gets the attribute value for TIMESIXPLACE using the alias name Timesixplace
     */
    public Date getTimesixplace() {
        return (Date) getAttributeInternal(TIMESIXPLACE);
    }

    /**Sets <code>value</code> as attribute value for TIMESIXPLACE using the alias name Timesixplace
     */
    public void setTimesixplace(Date value) {
        setAttributeInternal(TIMESIXPLACE, value);
    }

    /**Gets the attribute value for SIXPLACE using the alias name Sixplace
     */
    public String getSixplace() {
        return (String) getAttributeInternal(SIXPLACE);
    }

    /**Sets <code>value</code> as attribute value for SIXPLACE using the alias name Sixplace
     */
    public void setSixplace(String value) {
        setAttributeInternal(SIXPLACE, value);
    }

    /**Gets the attribute value for ONESECONDCLASSSEAT using the alias name Onesecondclassseat
     */
    public Number getOnesecondclassseat() {
        return (Number) getAttributeInternal(ONESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for ONESECONDCLASSSEAT using the alias name Onesecondclassseat
     */
    public void setOnesecondclassseat(Number value) {
        setAttributeInternal(ONESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for TWOSECONDCLASSSEAT using the alias name Twosecondclassseat
     */
    public Number getTwosecondclassseat() {
        return (Number) getAttributeInternal(TWOSECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for TWOSECONDCLASSSEAT using the alias name Twosecondclassseat
     */
    public void setTwosecondclassseat(Number value) {
        setAttributeInternal(TWOSECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for THREESECONDCLASSSEAT using the alias name Threesecondclassseat
     */
    public Number getThreesecondclassseat() {
        return (Number) getAttributeInternal(THREESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for THREESECONDCLASSSEAT using the alias name Threesecondclassseat
     */
    public void setThreesecondclassseat(Number value) {
        setAttributeInternal(THREESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for FORESECONDCLASSSEAT using the alias name Foresecondclassseat
     */
    public Number getForesecondclassseat() {
        return (Number) getAttributeInternal(FORESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for FORESECONDCLASSSEAT using the alias name Foresecondclassseat
     */
    public void setForesecondclassseat(Number value) {
        setAttributeInternal(FORESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for FIVESECONDCLASSSEAT using the alias name Fivesecondclassseat
     */
    public Number getFivesecondclassseat() {
        return (Number) getAttributeInternal(FIVESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for FIVESECONDCLASSSEAT using the alias name Fivesecondclassseat
     */
    public void setFivesecondclassseat(Number value) {
        setAttributeInternal(FIVESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for ONEFIRSTCLASSSEAT using the alias name Onefirstclassseat
     */
    public Number getOnefirstclassseat() {
        return (Number) getAttributeInternal(ONEFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for ONEFIRSTCLASSSEAT using the alias name Onefirstclassseat
     */
    public void setOnefirstclassseat(Number value) {
        setAttributeInternal(ONEFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for TWOFIRSTCLASSSEAT using the alias name Twofirstclassseat
     */
    public Number getTwofirstclassseat() {
        return (Number) getAttributeInternal(TWOFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for TWOFIRSTCLASSSEAT using the alias name Twofirstclassseat
     */
    public void setTwofirstclassseat(Number value) {
        setAttributeInternal(TWOFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for THREEFIRSTCLASSSEAT using the alias name Threefirstclassseat
     */
    public Number getThreefirstclassseat() {
        return (Number) getAttributeInternal(THREEFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for THREEFIRSTCLASSSEAT using the alias name Threefirstclassseat
     */
    public void setThreefirstclassseat(Number value) {
        setAttributeInternal(THREEFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for FOREFIRSTCLASSSEAT using the alias name Forefirstclassseat
     */
    public Number getForefirstclassseat() {
        return (Number) getAttributeInternal(FOREFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for FOREFIRSTCLASSSEAT using the alias name Forefirstclassseat
     */
    public void setForefirstclassseat(Number value) {
        setAttributeInternal(FOREFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for FIVEFIRSTCLASSSEAT using the alias name Fivefirstclassseat
     */
    public Number getFivefirstclassseat() {
        return (Number) getAttributeInternal(FIVEFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for FIVEFIRSTCLASSSEAT using the alias name Fivefirstclassseat
     */
    public void setFivefirstclassseat(Number value) {
        setAttributeInternal(FIVEFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for ONEBUSINESSCLASSSEAT using the alias name Onebusinessclassseat
     */
    public Number getOnebusinessclassseat() {
        return (Number) getAttributeInternal(ONEBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for ONEBUSINESSCLASSSEAT using the alias name Onebusinessclassseat
     */
    public void setOnebusinessclassseat(Number value) {
        setAttributeInternal(ONEBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for TWOBUSINESSCLASSSEAT using the alias name Twobusinessclassseat
     */
    public Number getTwobusinessclassseat() {
        return (Number) getAttributeInternal(TWOBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for TWOBUSINESSCLASSSEAT using the alias name Twobusinessclassseat
     */
    public void setTwobusinessclassseat(Number value) {
        setAttributeInternal(TWOBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for THREEBUSINESSCLASSSEAT using the alias name Threebusinessclassseat
     */
    public Number getThreebusinessclassseat() {
        return (Number) getAttributeInternal(THREEBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for THREEBUSINESSCLASSSEAT using the alias name Threebusinessclassseat
     */
    public void setThreebusinessclassseat(Number value) {
        setAttributeInternal(THREEBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for FOREBUSINESSCLASSSEAT using the alias name Forebusinessclassseat
     */
    public Number getForebusinessclassseat() {
        return (Number) getAttributeInternal(FOREBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for FOREBUSINESSCLASSSEAT using the alias name Forebusinessclassseat
     */
    public void setForebusinessclassseat(Number value) {
        setAttributeInternal(FOREBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for FIVEBUSINESSCLASSSEAT using the alias name Fivebusinessclassseat
     */
    public Number getFivebusinessclassseat() {
        return (Number) getAttributeInternal(FIVEBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as attribute value for FIVEBUSINESSCLASSSEAT using the alias name Fivebusinessclassseat
     */
    public void setFivebusinessclassseat(Number value) {
        setAttributeInternal(FIVEBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for NUMBERCOLUMN using the alias name Numbercolumn
     */
    public Number getNumbercolumn() {
        return (Number) getAttributeInternal(NUMBERCOLUMN);
    }

    /**Sets <code>value</code> as attribute value for NUMBERCOLUMN using the alias name Numbercolumn
     */
    public void setNumbercolumn(Number value) {
        setAttributeInternal(NUMBERCOLUMN, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute Ymd
     */
    public String getYmd() {
        return (String) getAttributeInternal(YMD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Ymd
     */
    public void setYmd(String value) {
        setAttributeInternal(YMD, value);
    }

    /**Gets the attribute value for the calculated attribute Startplace
     */
    public String getStartplace() {
        return (String) getAttributeInternal(STARTPLACE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Startplace
     */
    public void setStartplace(String value) {
        setAttributeInternal(STARTPLACE, value);
    }

    /**Gets the attribute value for the calculated attribute Destinationplace
     */
    public String getDestinationplace() {
        return (String) getAttributeInternal(DESTINATIONPLACE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Destinationplace
     */
    public void setDestinationplace(String value) {
        setAttributeInternal(DESTINATIONPLACE, value);
    }

    /**Gets the attribute value for the calculated attribute Starttime
     */
    public String getStarttime() {
        return (String) getAttributeInternal(STARTTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Starttime
     */
    public void setStarttime(String value) {
        setAttributeInternal(STARTTIME, value);
    }

    /**Gets the attribute value for the calculated attribute Endtime
     */
    public String getEndtime() {
        return (String) getAttributeInternal(ENDTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Endtime
     */
    public void setEndtime(String value) {
        setAttributeInternal(ENDTIME, value);
    }

    /**Gets the attribute value for the calculated attribute Alltime
     */
    public String getAlltime() {
        return (String) getAttributeInternal(ALLTIME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Alltime
     */
    public void setAlltime(String value) {
        setAttributeInternal(ALLTIME, value);
    }

    /**Gets the attribute value for the calculated attribute Price
     */
    public String getPrice() {
        return (String) getAttributeInternal(PRICE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Price
     */
    public void setPrice(String value) {
        setAttributeInternal(PRICE, value);
    }

    /**Gets the attribute value for the calculated attribute Sortseat
     */
    public String getSortseat() {
        return (String) getAttributeInternal(SORTSEAT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sortseat
     */
    public void setSortseat(String value) {
        setAttributeInternal(SORTSEAT, value);
    }

    /**Gets the attribute value for the calculated attribute Pricethree
     */
    public String getPricethree() {
        return (String) getAttributeInternal(PRICETHREE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Pricethree
     */
    public void setPricethree(String value) {
        setAttributeInternal(PRICETHREE, value);
    }

    /**Gets the attribute value for the calculated attribute Countseat
     */
    public String getCountseat() {
        return (String) getAttributeInternal(COUNTSEAT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Countseat
     */
    public void setCountseat(String value) {
        setAttributeInternal(COUNTSEAT, value);
    }

    /**Gets the attribute value for the calculated attribute Namecustomer
     */
    public String getNamecustomer() {
        return (String) getAttributeInternal(NAMECUSTOMER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Namecustomer
     */
    public void setNamecustomer(String value) {
        setAttributeInternal(NAMECUSTOMER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDNUM:
            return getIdnum();
        case TRAINNAME:
            return getTrainname();
        case TIMEONEPLACE:
            return getTimeoneplace();
        case ONEPLACE:
            return getOneplace();
        case PRICESECONDOFONEPART:
            return getPricesecondofonepart();
        case PRICEFIRSTOFONEPART:
            return getPricefirstofonepart();
        case PRICEBUSINESSOFONEPART:
            return getPricebusinessofonepart();
        case TIMETWOPLACE:
            return getTimetwoplace();
        case TWOPLACE:
            return getTwoplace();
        case PRICESECONDOFTWOPART:
            return getPricesecondoftwopart();
        case PRICEFIRSTOFTWOPART:
            return getPricefirstoftwopart();
        case PRICEBUSINESSOFTWOPART:
            return getPricebusinessoftwopart();
        case TIMETHREEPLACE:
            return getTimethreeplace();
        case THREEPLACE:
            return getThreeplace();
        case PRICESECONDOFTHREEPART:
            return getPricesecondofthreepart();
        case PRICEFIRSTOFTHREEPART:
            return getPricefirstofthreepart();
        case PRICEBUSINESSOFTHREEPART:
            return getPricebusinessofthreepart();
        case TIMEFOREPLACE:
            return getTimeforeplace();
        case FOREPLACE:
            return getForeplace();
        case PRICESECONDOFFOREPART:
            return getPricesecondofforepart();
        case PRICEFIRSTOFFOREPART:
            return getPricefirstofforepart();
        case PRICEBUSINESSOFFOREPART:
            return getPricebusinessofforepart();
        case TIMEFIVEPLACE:
            return getTimefiveplace();
        case FIVEPLACE:
            return getFiveplace();
        case PRICESECONDOFFIVEPART:
            return getPricesecondoffivepart();
        case PRICEFIRSTOFFIVEPART:
            return getPricefirstoffivepart();
        case PRICEBUSINESSOFFIVEPART:
            return getPricebusinessoffivepart();
        case TIMESIXPLACE:
            return getTimesixplace();
        case SIXPLACE:
            return getSixplace();
        case ONESECONDCLASSSEAT:
            return getOnesecondclassseat();
        case TWOSECONDCLASSSEAT:
            return getTwosecondclassseat();
        case THREESECONDCLASSSEAT:
            return getThreesecondclassseat();
        case FORESECONDCLASSSEAT:
            return getForesecondclassseat();
        case FIVESECONDCLASSSEAT:
            return getFivesecondclassseat();
        case ONEFIRSTCLASSSEAT:
            return getOnefirstclassseat();
        case TWOFIRSTCLASSSEAT:
            return getTwofirstclassseat();
        case THREEFIRSTCLASSSEAT:
            return getThreefirstclassseat();
        case FOREFIRSTCLASSSEAT:
            return getForefirstclassseat();
        case FIVEFIRSTCLASSSEAT:
            return getFivefirstclassseat();
        case ONEBUSINESSCLASSSEAT:
            return getOnebusinessclassseat();
        case TWOBUSINESSCLASSSEAT:
            return getTwobusinessclassseat();
        case THREEBUSINESSCLASSSEAT:
            return getThreebusinessclassseat();
        case FOREBUSINESSCLASSSEAT:
            return getForebusinessclassseat();
        case FIVEBUSINESSCLASSSEAT:
            return getFivebusinessclassseat();
        case NUMBERCOLUMN:
            return getNumbercolumn();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case YMD:
            return getYmd();
        case STARTPLACE:
            return getStartplace();
        case DESTINATIONPLACE:
            return getDestinationplace();
        case STARTTIME:
            return getStarttime();
        case ENDTIME:
            return getEndtime();
        case ALLTIME:
            return getAlltime();
        case PRICE:
            return getPrice();
        case SORTSEAT:
            return getSortseat();
        case PRICETHREE:
            return getPricethree();
        case COUNTSEAT:
            return getCountseat();
        case NAMECUSTOMER:
            return getNamecustomer();
        case IDCUSTOMER:
            return getIdcustomer();
        case IDNUMCHANGE:
            return getIdnumchange();
        case IDTRAINCHANGE:
            return getIdtrainchange();
        case STARTSTATIONCHANGE:
            return getStartstationchange();
        case ENDSTATIONCHANGE:
            return getEndstationchange();
        case SEATCLASSCHANGE:
            return getSeatclasschange();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDNUM:
            setIdnum((Number)value);
            return;
        case TRAINNAME:
            setTrainname((String)value);
            return;
        case TIMEONEPLACE:
            setTimeoneplace((Date)value);
            return;
        case ONEPLACE:
            setOneplace((String)value);
            return;
        case PRICESECONDOFONEPART:
            setPricesecondofonepart((Number)value);
            return;
        case PRICEFIRSTOFONEPART:
            setPricefirstofonepart((Number)value);
            return;
        case PRICEBUSINESSOFONEPART:
            setPricebusinessofonepart((Number)value);
            return;
        case TIMETWOPLACE:
            setTimetwoplace((Date)value);
            return;
        case TWOPLACE:
            setTwoplace((String)value);
            return;
        case PRICESECONDOFTWOPART:
            setPricesecondoftwopart((Number)value);
            return;
        case PRICEFIRSTOFTWOPART:
            setPricefirstoftwopart((Number)value);
            return;
        case PRICEBUSINESSOFTWOPART:
            setPricebusinessoftwopart((Number)value);
            return;
        case TIMETHREEPLACE:
            setTimethreeplace((Date)value);
            return;
        case THREEPLACE:
            setThreeplace((String)value);
            return;
        case PRICESECONDOFTHREEPART:
            setPricesecondofthreepart((Number)value);
            return;
        case PRICEFIRSTOFTHREEPART:
            setPricefirstofthreepart((Number)value);
            return;
        case PRICEBUSINESSOFTHREEPART:
            setPricebusinessofthreepart((Number)value);
            return;
        case TIMEFOREPLACE:
            setTimeforeplace((Date)value);
            return;
        case FOREPLACE:
            setForeplace((String)value);
            return;
        case PRICESECONDOFFOREPART:
            setPricesecondofforepart((Number)value);
            return;
        case PRICEFIRSTOFFOREPART:
            setPricefirstofforepart((Number)value);
            return;
        case PRICEBUSINESSOFFOREPART:
            setPricebusinessofforepart((Number)value);
            return;
        case TIMEFIVEPLACE:
            setTimefiveplace((Date)value);
            return;
        case FIVEPLACE:
            setFiveplace((String)value);
            return;
        case PRICESECONDOFFIVEPART:
            setPricesecondoffivepart((Number)value);
            return;
        case PRICEFIRSTOFFIVEPART:
            setPricefirstoffivepart((Number)value);
            return;
        case PRICEBUSINESSOFFIVEPART:
            setPricebusinessoffivepart((Number)value);
            return;
        case TIMESIXPLACE:
            setTimesixplace((Date)value);
            return;
        case SIXPLACE:
            setSixplace((String)value);
            return;
        case ONESECONDCLASSSEAT:
            setOnesecondclassseat((Number)value);
            return;
        case TWOSECONDCLASSSEAT:
            setTwosecondclassseat((Number)value);
            return;
        case THREESECONDCLASSSEAT:
            setThreesecondclassseat((Number)value);
            return;
        case FORESECONDCLASSSEAT:
            setForesecondclassseat((Number)value);
            return;
        case FIVESECONDCLASSSEAT:
            setFivesecondclassseat((Number)value);
            return;
        case ONEFIRSTCLASSSEAT:
            setOnefirstclassseat((Number)value);
            return;
        case TWOFIRSTCLASSSEAT:
            setTwofirstclassseat((Number)value);
            return;
        case THREEFIRSTCLASSSEAT:
            setThreefirstclassseat((Number)value);
            return;
        case FOREFIRSTCLASSSEAT:
            setForefirstclassseat((Number)value);
            return;
        case FIVEFIRSTCLASSSEAT:
            setFivefirstclassseat((Number)value);
            return;
        case ONEBUSINESSCLASSSEAT:
            setOnebusinessclassseat((Number)value);
            return;
        case TWOBUSINESSCLASSSEAT:
            setTwobusinessclassseat((Number)value);
            return;
        case THREEBUSINESSCLASSSEAT:
            setThreebusinessclassseat((Number)value);
            return;
        case FOREBUSINESSCLASSSEAT:
            setForebusinessclassseat((Number)value);
            return;
        case FIVEBUSINESSCLASSSEAT:
            setFivebusinessclassseat((Number)value);
            return;
        case NUMBERCOLUMN:
            setNumbercolumn((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case YMD:
            setYmd((String)value);
            return;
        case STARTPLACE:
            setStartplace((String)value);
            return;
        case DESTINATIONPLACE:
            setDestinationplace((String)value);
            return;
        case STARTTIME:
            setStarttime((String)value);
            return;
        case ENDTIME:
            setEndtime((String)value);
            return;
        case ALLTIME:
            setAlltime((String)value);
            return;
        case PRICE:
            setPrice((String)value);
            return;
        case SORTSEAT:
            setSortseat((String)value);
            return;
        case PRICETHREE:
            setPricethree((String)value);
            return;
        case COUNTSEAT:
            setCountseat((String)value);
            return;
        case NAMECUSTOMER:
            setNamecustomer((String)value);
            return;
        case IDCUSTOMER:
            setIdcustomer((String)value);
            return;
        case IDNUMCHANGE:
            setIdnumchange((String)value);
            return;
        case IDTRAINCHANGE:
            setIdtrainchange((String)value);
            return;
        case STARTSTATIONCHANGE:
            setStartstationchange((String)value);
            return;
        case ENDSTATIONCHANGE:
            setEndstationchange((String)value);
            return;
        case SEATCLASSCHANGE:
            setSeatclasschange((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Idcustomer
     */
    public String getIdcustomer() {
        return (String) getAttributeInternal(IDCUSTOMER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idcustomer
     */
    public void setIdcustomer(String value) {
        setAttributeInternal(IDCUSTOMER, value);
    }

    /**Gets the attribute value for the calculated attribute Idnumchange
     */
    public String getIdnumchange() {
        return (String) getAttributeInternal(IDNUMCHANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idnumchange
     */
    public void setIdnumchange(String value) {
        setAttributeInternal(IDNUMCHANGE, value);
    }

    /**Gets the attribute value for the calculated attribute Idtrainchange
     */
    public String getIdtrainchange() {
        return (String) getAttributeInternal(IDTRAINCHANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Idtrainchange
     */
    public void setIdtrainchange(String value) {
        setAttributeInternal(IDTRAINCHANGE, value);
    }

    /**Gets the attribute value for the calculated attribute Startstationchange
     */
    public String getStartstationchange() {
        return (String) getAttributeInternal(STARTSTATIONCHANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Startstationchange
     */
    public void setStartstationchange(String value) {
        setAttributeInternal(STARTSTATIONCHANGE, value);
    }

    /**Gets the attribute value for the calculated attribute Endstationchange
     */
    public String getEndstationchange() {
        return (String) getAttributeInternal(ENDSTATIONCHANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Endstationchange
     */
    public void setEndstationchange(String value) {
        setAttributeInternal(ENDSTATIONCHANGE, value);
    }

    /**Gets the attribute value for the calculated attribute Seatclasschange
     */
    public String getSeatclasschange() {
        return (String) getAttributeInternal(SEATCLASSCHANGE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Seatclasschange
     */
    public void setSeatclasschange(String value) {
        setAttributeInternal(SEATCLASSCHANGE, value);
    }
}
