package oracle.apps.ak.tickets.schema;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class loginEOImpl extends OAEntityImpl {
    public static final int IDNUM = 0;
    public static final int LOGINNUM = 1;
    public static final int LOGINPASSWORD = 2;
    public static final int ENAME = 3;
    public static final int IDCARD = 4;
    public static final int PHONE = 5;
    public static final int LASTUPDATEDATE = 6;
    public static final int LASTUPDATEDBY = 7;
    public static final int CREATIONDATE = 8;
    public static final int CREATEDBY = 9;
    public static final int LASTUPDATELOGIN = 10;
    public static final int SEX = 11;
    public static final int IDENT = 12;
    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public loginEOImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.ak.tickets.schema.loginEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for Idnum, using the alias name Idnum
     */
    public Number getIdnum() {
        return (Number)getAttributeInternal(IDNUM);
    }

    /**Sets <code>value</code> as the attribute value for Idnum
     */
    public void setIdnum(Number value) {
        setAttributeInternal(IDNUM, value);
    }

    /**Gets the attribute value for Loginnum, using the alias name Loginnum
     */
    public String getLoginnum() {
        return (String)getAttributeInternal(LOGINNUM);
    }

    /**Sets <code>value</code> as the attribute value for Loginnum
     */
    public void setLoginnum(String value) {
        setAttributeInternal(LOGINNUM, value);
    }

    /**Gets the attribute value for Loginpassword, using the alias name Loginpassword
     */
    public String getLoginpassword() {
        return (String)getAttributeInternal(LOGINPASSWORD);
    }

    /**Sets <code>value</code> as the attribute value for Loginpassword
     */
    public void setLoginpassword(String value) {
        setAttributeInternal(LOGINPASSWORD, value);
    }

    /**Gets the attribute value for Ename, using the alias name Ename
     */
    public String getEname() {
        return (String)getAttributeInternal(ENAME);
    }

    /**Sets <code>value</code> as the attribute value for Ename
     */
    public void setEname(String value) {
        setAttributeInternal(ENAME, value);
    }

    /**Gets the attribute value for Idcard, using the alias name Idcard
     */
    public String getIdcard() {
        return (String)getAttributeInternal(IDCARD);
    }

    /**Sets <code>value</code> as the attribute value for Idcard
     */
    public void setIdcard(String value) {
        setAttributeInternal(IDCARD, value);
    }

    /**Gets the attribute value for Phone, using the alias name Phone
     */
    public Number getPhone() {
        return (Number)getAttributeInternal(PHONE);
    }

    /**Sets <code>value</code> as the attribute value for Phone
     */
    public void setPhone(Number value) {
        setAttributeInternal(PHONE, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for Sex, using the alias name Sex
     */
    public String getSex() {
        return (String)getAttributeInternal(SEX);
    }

    /**Sets <code>value</code> as the attribute value for Sex
     */
    public void setSex(String value) {
        setAttributeInternal(SEX, value);
    }

    /**Gets the attribute value for Ident, using the alias name Ident
     */
    public String getIdent() {
        return (String)getAttributeInternal(IDENT);
    }

    /**Sets <code>value</code> as the attribute value for Ident
     */
    public void setIdent(String value) {
        setAttributeInternal(IDENT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDNUM:
            return getIdnum();
        case LOGINNUM:
            return getLoginnum();
        case LOGINPASSWORD:
            return getLoginpassword();
        case ENAME:
            return getEname();
        case IDCARD:
            return getIdcard();
        case PHONE:
            return getPhone();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case SEX:
            return getSex();
        case IDENT:
            return getIdent();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDNUM:
            setIdnum((Number)value);
            return;
        case LOGINNUM:
            setLoginnum((String)value);
            return;
        case LOGINPASSWORD:
            setLoginpassword((String)value);
            return;
        case ENAME:
            setEname((String)value);
            return;
        case IDCARD:
            setIdcard((String)value);
            return;
        case PHONE:
            setPhone((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case SEX:
            setSex((String)value);
            return;
        case IDENT:
            setIdent((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idnum) {
        return new Key(new Object[]{idnum});
    }
}
