package oracle.apps.ak.tickets.schema;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class trainEOImpl extends OAEntityImpl {
    public static final int IDNUM = 0;
    public static final int TRAINNAME = 1;
    public static final int TIMEONEPLACE = 2;
    public static final int ONEPLACE = 3;
    public static final int PRICESECONDOFONEPART = 4;
    public static final int PRICEFIRSTOFONEPART = 5;
    public static final int PRICEBUSINESSOFONEPART = 6;
    public static final int TIMETWOPLACE = 7;
    public static final int TWOPLACE = 8;
    public static final int PRICESECONDOFTWOPART = 9;
    public static final int PRICEFIRSTOFTWOPART = 10;
    public static final int PRICEBUSINESSOFTWOPART = 11;
    public static final int TIMETHREEPLACE = 12;
    public static final int THREEPLACE = 13;
    public static final int PRICESECONDOFTHREEPART = 14;
    public static final int PRICEFIRSTOFTHREEPART = 15;
    public static final int PRICEBUSINESSOFTHREEPART = 16;
    public static final int TIMEFOREPLACE = 17;
    public static final int FOREPLACE = 18;
    public static final int PRICESECONDOFFOREPART = 19;
    public static final int PRICEFIRSTOFFOREPART = 20;
    public static final int PRICEBUSINESSOFFOREPART = 21;
    public static final int TIMEFIVEPLACE = 22;
    public static final int FIVEPLACE = 23;
    public static final int PRICESECONDOFFIVEPART = 24;
    public static final int PRICEFIRSTOFFIVEPART = 25;
    public static final int PRICEBUSINESSOFFIVEPART = 26;
    public static final int TIMESIXPLACE = 27;
    public static final int SIXPLACE = 28;
    public static final int ONESECONDCLASSSEAT = 29;
    public static final int TWOSECONDCLASSSEAT = 30;
    public static final int THREESECONDCLASSSEAT = 31;
    public static final int FORESECONDCLASSSEAT = 32;
    public static final int FIVESECONDCLASSSEAT = 33;
    public static final int ONEFIRSTCLASSSEAT = 34;
    public static final int TWOFIRSTCLASSSEAT = 35;
    public static final int THREEFIRSTCLASSSEAT = 36;
    public static final int FOREFIRSTCLASSSEAT = 37;
    public static final int FIVEFIRSTCLASSSEAT = 38;
    public static final int ONEBUSINESSCLASSSEAT = 39;
    public static final int TWOBUSINESSCLASSSEAT = 40;
    public static final int THREEBUSINESSCLASSSEAT = 41;
    public static final int FOREBUSINESSCLASSSEAT = 42;
    public static final int FIVEBUSINESSCLASSSEAT = 43;
    public static final int NUMBERCOLUMN = 44;
    public static final int LASTUPDATEDATE = 45;
    public static final int LASTUPDATEDBY = 46;
    public static final int CREATIONDATE = 47;
    public static final int CREATEDBY = 48;
    public static final int LASTUPDATELOGIN = 49;
    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public trainEOImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.ak.tickets.schema.trainEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for Idnum, using the alias name Idnum
     */
    public Number getIdnum() {
        return (Number)getAttributeInternal(IDNUM);
    }

    /**Sets <code>value</code> as the attribute value for Idnum
     */
    public void setIdnum(Number value) {
        setAttributeInternal(IDNUM, value);
    }

    /**Gets the attribute value for Trainname, using the alias name Trainname
     */
    public String getTrainname() {
        return (String)getAttributeInternal(TRAINNAME);
    }

    /**Sets <code>value</code> as the attribute value for Trainname
     */
    public void setTrainname(String value) {
        setAttributeInternal(TRAINNAME, value);
    }

    /**Gets the attribute value for Timeoneplace, using the alias name Timeoneplace
     */
    public Date getTimeoneplace() {
        return (Date)getAttributeInternal(TIMEONEPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Timeoneplace
     */
    public void setTimeoneplace(Date value) {
        setAttributeInternal(TIMEONEPLACE, value);
    }

    /**Gets the attribute value for Oneplace, using the alias name Oneplace
     */
    public String getOneplace() {
        return (String)getAttributeInternal(ONEPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Oneplace
     */
    public void setOneplace(String value) {
        setAttributeInternal(ONEPLACE, value);
    }

    /**Gets the attribute value for Pricesecondofonepart, using the alias name Pricesecondofonepart
     */
    public Number getPricesecondofonepart() {
        return (Number)getAttributeInternal(PRICESECONDOFONEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricesecondofonepart
     */
    public void setPricesecondofonepart(Number value) {
        setAttributeInternal(PRICESECONDOFONEPART, value);
    }

    /**Gets the attribute value for Pricefirstofonepart, using the alias name Pricefirstofonepart
     */
    public Number getPricefirstofonepart() {
        return (Number)getAttributeInternal(PRICEFIRSTOFONEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricefirstofonepart
     */
    public void setPricefirstofonepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFONEPART, value);
    }

    /**Gets the attribute value for Pricebusinessofonepart, using the alias name Pricebusinessofonepart
     */
    public Number getPricebusinessofonepart() {
        return (Number)getAttributeInternal(PRICEBUSINESSOFONEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricebusinessofonepart
     */
    public void setPricebusinessofonepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFONEPART, value);
    }

    /**Gets the attribute value for Timetwoplace, using the alias name Timetwoplace
     */
    public Date getTimetwoplace() {
        return (Date)getAttributeInternal(TIMETWOPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Timetwoplace
     */
    public void setTimetwoplace(Date value) {
        setAttributeInternal(TIMETWOPLACE, value);
    }

    /**Gets the attribute value for Twoplace, using the alias name Twoplace
     */
    public String getTwoplace() {
        return (String)getAttributeInternal(TWOPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Twoplace
     */
    public void setTwoplace(String value) {
        setAttributeInternal(TWOPLACE, value);
    }

    /**Gets the attribute value for Pricesecondoftwopart, using the alias name Pricesecondoftwopart
     */
    public Number getPricesecondoftwopart() {
        return (Number)getAttributeInternal(PRICESECONDOFTWOPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricesecondoftwopart
     */
    public void setPricesecondoftwopart(Number value) {
        setAttributeInternal(PRICESECONDOFTWOPART, value);
    }

    /**Gets the attribute value for Pricefirstoftwopart, using the alias name Pricefirstoftwopart
     */
    public Number getPricefirstoftwopart() {
        return (Number)getAttributeInternal(PRICEFIRSTOFTWOPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricefirstoftwopart
     */
    public void setPricefirstoftwopart(Number value) {
        setAttributeInternal(PRICEFIRSTOFTWOPART, value);
    }

    /**Gets the attribute value for Pricebusinessoftwopart, using the alias name Pricebusinessoftwopart
     */
    public Number getPricebusinessoftwopart() {
        return (Number)getAttributeInternal(PRICEBUSINESSOFTWOPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricebusinessoftwopart
     */
    public void setPricebusinessoftwopart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFTWOPART, value);
    }

    /**Gets the attribute value for Timethreeplace, using the alias name Timethreeplace
     */
    public Date getTimethreeplace() {
        return (Date)getAttributeInternal(TIMETHREEPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Timethreeplace
     */
    public void setTimethreeplace(Date value) {
        setAttributeInternal(TIMETHREEPLACE, value);
    }

    /**Gets the attribute value for Threeplace, using the alias name Threeplace
     */
    public String getThreeplace() {
        return (String)getAttributeInternal(THREEPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Threeplace
     */
    public void setThreeplace(String value) {
        setAttributeInternal(THREEPLACE, value);
    }

    /**Gets the attribute value for Pricesecondofthreepart, using the alias name Pricesecondofthreepart
     */
    public Number getPricesecondofthreepart() {
        return (Number)getAttributeInternal(PRICESECONDOFTHREEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricesecondofthreepart
     */
    public void setPricesecondofthreepart(Number value) {
        setAttributeInternal(PRICESECONDOFTHREEPART, value);
    }

    /**Gets the attribute value for Pricefirstofthreepart, using the alias name Pricefirstofthreepart
     */
    public Number getPricefirstofthreepart() {
        return (Number)getAttributeInternal(PRICEFIRSTOFTHREEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricefirstofthreepart
     */
    public void setPricefirstofthreepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFTHREEPART, value);
    }

    /**Gets the attribute value for Pricebusinessofthreepart, using the alias name Pricebusinessofthreepart
     */
    public Number getPricebusinessofthreepart() {
        return (Number)getAttributeInternal(PRICEBUSINESSOFTHREEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricebusinessofthreepart
     */
    public void setPricebusinessofthreepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFTHREEPART, value);
    }

    /**Gets the attribute value for Timeforeplace, using the alias name Timeforeplace
     */
    public Date getTimeforeplace() {
        return (Date)getAttributeInternal(TIMEFOREPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Timeforeplace
     */
    public void setTimeforeplace(Date value) {
        setAttributeInternal(TIMEFOREPLACE, value);
    }

    /**Gets the attribute value for Foreplace, using the alias name Foreplace
     */
    public String getForeplace() {
        return (String)getAttributeInternal(FOREPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Foreplace
     */
    public void setForeplace(String value) {
        setAttributeInternal(FOREPLACE, value);
    }

    /**Gets the attribute value for Pricesecondofforepart, using the alias name Pricesecondofforepart
     */
    public Number getPricesecondofforepart() {
        return (Number)getAttributeInternal(PRICESECONDOFFOREPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricesecondofforepart
     */
    public void setPricesecondofforepart(Number value) {
        setAttributeInternal(PRICESECONDOFFOREPART, value);
    }

    /**Gets the attribute value for Pricefirstofforepart, using the alias name Pricefirstofforepart
     */
    public Number getPricefirstofforepart() {
        return (Number)getAttributeInternal(PRICEFIRSTOFFOREPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricefirstofforepart
     */
    public void setPricefirstofforepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFFOREPART, value);
    }

    /**Gets the attribute value for Pricebusinessofforepart, using the alias name Pricebusinessofforepart
     */
    public Number getPricebusinessofforepart() {
        return (Number)getAttributeInternal(PRICEBUSINESSOFFOREPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricebusinessofforepart
     */
    public void setPricebusinessofforepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFFOREPART, value);
    }

    /**Gets the attribute value for Timefiveplace, using the alias name Timefiveplace
     */
    public Date getTimefiveplace() {
        return (Date)getAttributeInternal(TIMEFIVEPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Timefiveplace
     */
    public void setTimefiveplace(Date value) {
        setAttributeInternal(TIMEFIVEPLACE, value);
    }

    /**Gets the attribute value for Fiveplace, using the alias name Fiveplace
     */
    public String getFiveplace() {
        return (String)getAttributeInternal(FIVEPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Fiveplace
     */
    public void setFiveplace(String value) {
        setAttributeInternal(FIVEPLACE, value);
    }

    /**Gets the attribute value for Pricesecondoffivepart, using the alias name Pricesecondoffivepart
     */
    public Number getPricesecondoffivepart() {
        return (Number)getAttributeInternal(PRICESECONDOFFIVEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricesecondoffivepart
     */
    public void setPricesecondoffivepart(Number value) {
        setAttributeInternal(PRICESECONDOFFIVEPART, value);
    }

    /**Gets the attribute value for Pricefirstoffivepart, using the alias name Pricefirstoffivepart
     */
    public Number getPricefirstoffivepart() {
        return (Number)getAttributeInternal(PRICEFIRSTOFFIVEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricefirstoffivepart
     */
    public void setPricefirstoffivepart(Number value) {
        setAttributeInternal(PRICEFIRSTOFFIVEPART, value);
    }

    /**Gets the attribute value for Pricebusinessoffivepart, using the alias name Pricebusinessoffivepart
     */
    public Number getPricebusinessoffivepart() {
        return (Number)getAttributeInternal(PRICEBUSINESSOFFIVEPART);
    }

    /**Sets <code>value</code> as the attribute value for Pricebusinessoffivepart
     */
    public void setPricebusinessoffivepart(Number value) {
        setAttributeInternal(PRICEBUSINESSOFFIVEPART, value);
    }

    /**Gets the attribute value for Timesixplace, using the alias name Timesixplace
     */
    public Date getTimesixplace() {
        return (Date)getAttributeInternal(TIMESIXPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Timesixplace
     */
    public void setTimesixplace(Date value) {
        setAttributeInternal(TIMESIXPLACE, value);
    }

    /**Gets the attribute value for Sixplace, using the alias name Sixplace
     */
    public String getSixplace() {
        return (String)getAttributeInternal(SIXPLACE);
    }

    /**Sets <code>value</code> as the attribute value for Sixplace
     */
    public void setSixplace(String value) {
        setAttributeInternal(SIXPLACE, value);
    }

    /**Gets the attribute value for Onesecondclassseat, using the alias name Onesecondclassseat
     */
    public Number getOnesecondclassseat() {
        return (Number)getAttributeInternal(ONESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Onesecondclassseat
     */
    public void setOnesecondclassseat(Number value) {
    
        setAttributeInternal(ONESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for Twosecondclassseat, using the alias name Twosecondclassseat
     */
    public Number getTwosecondclassseat() {
        return (Number)getAttributeInternal(TWOSECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Twosecondclassseat
     */
    public void setTwosecondclassseat(Number value) {
        setAttributeInternal(TWOSECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for Threesecondclassseat, using the alias name Threesecondclassseat
     */
    public Number getThreesecondclassseat() {
        return (Number)getAttributeInternal(THREESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Threesecondclassseat
     */
    public void setThreesecondclassseat(Number value) {
        setAttributeInternal(THREESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for Foresecondclassseat, using the alias name Foresecondclassseat
     */
    public Number getForesecondclassseat() {
        return (Number)getAttributeInternal(FORESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Foresecondclassseat
     */
    public void setForesecondclassseat(Number value) {
        setAttributeInternal(FORESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for Fivesecondclassseat, using the alias name Fivesecondclassseat
     */
    public Number getFivesecondclassseat() {
        return (Number)getAttributeInternal(FIVESECONDCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Fivesecondclassseat
     */
    public void setFivesecondclassseat(Number value) {
        setAttributeInternal(FIVESECONDCLASSSEAT, value);
    }

    /**Gets the attribute value for Onefirstclassseat, using the alias name Onefirstclassseat
     */
    public Number getOnefirstclassseat() {
        return (Number)getAttributeInternal(ONEFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Onefirstclassseat
     */
    public void setOnefirstclassseat(Number value) {
        setAttributeInternal(ONEFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for Twofirstclassseat, using the alias name Twofirstclassseat
     */
    public Number getTwofirstclassseat() {
        return (Number)getAttributeInternal(TWOFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Twofirstclassseat
     */
    public void setTwofirstclassseat(Number value) {
        setAttributeInternal(TWOFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for Threefirstclassseat, using the alias name Threefirstclassseat
     */
    public Number getThreefirstclassseat() {
        return (Number)getAttributeInternal(THREEFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Threefirstclassseat
     */
    public void setThreefirstclassseat(Number value) {
        setAttributeInternal(THREEFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for Forefirstclassseat, using the alias name Forefirstclassseat
     */
    public Number getForefirstclassseat() {
        return (Number)getAttributeInternal(FOREFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Forefirstclassseat
     */
    public void setForefirstclassseat(Number value) {
        setAttributeInternal(FOREFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for Fivefirstclassseat, using the alias name Fivefirstclassseat
     */
    public Number getFivefirstclassseat() {
        return (Number)getAttributeInternal(FIVEFIRSTCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Fivefirstclassseat
     */
    public void setFivefirstclassseat(Number value) {
        setAttributeInternal(FIVEFIRSTCLASSSEAT, value);
    }

    /**Gets the attribute value for Onebusinessclassseat, using the alias name Onebusinessclassseat
     */
    public Number getOnebusinessclassseat() {
        return (Number)getAttributeInternal(ONEBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Onebusinessclassseat
     */
    public void setOnebusinessclassseat(Number value) {
        setAttributeInternal(ONEBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for Twobusinessclassseat, using the alias name Twobusinessclassseat
     */
    public Number getTwobusinessclassseat() {
        return (Number)getAttributeInternal(TWOBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Twobusinessclassseat
     */
    public void setTwobusinessclassseat(Number value) {
        setAttributeInternal(TWOBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for Threebusinessclassseat, using the alias name Threebusinessclassseat
     */
    public Number getThreebusinessclassseat() {
        return (Number)getAttributeInternal(THREEBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Threebusinessclassseat
     */
    public void setThreebusinessclassseat(Number value) {
        setAttributeInternal(THREEBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for Forebusinessclassseat, using the alias name Forebusinessclassseat
     */
    public Number getForebusinessclassseat() {
        return (Number)getAttributeInternal(FOREBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Forebusinessclassseat
     */
    public void setForebusinessclassseat(Number value) {
        setAttributeInternal(FOREBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for Fivebusinessclassseat, using the alias name Fivebusinessclassseat
     */
    public Number getFivebusinessclassseat() {
        return (Number)getAttributeInternal(FIVEBUSINESSCLASSSEAT);
    }

    /**Sets <code>value</code> as the attribute value for Fivebusinessclassseat
     */
    public void setFivebusinessclassseat(Number value) {
        setAttributeInternal(FIVEBUSINESSCLASSSEAT, value);
    }

    /**Gets the attribute value for Numbercolumn, using the alias name Numbercolumn
     */
    public Number getNumbercolumn() {
        return (Number)getAttributeInternal(NUMBERCOLUMN);
    }

    /**Sets <code>value</code> as the attribute value for Numbercolumn
     */
    public void setNumbercolumn(Number value) {
        setAttributeInternal(NUMBERCOLUMN, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDNUM:
            return getIdnum();
        case TRAINNAME:
            return getTrainname();
        case TIMEONEPLACE:
            return getTimeoneplace();
        case ONEPLACE:
            return getOneplace();
        case PRICESECONDOFONEPART:
            return getPricesecondofonepart();
        case PRICEFIRSTOFONEPART:
            return getPricefirstofonepart();
        case PRICEBUSINESSOFONEPART:
            return getPricebusinessofonepart();
        case TIMETWOPLACE:
            return getTimetwoplace();
        case TWOPLACE:
            return getTwoplace();
        case PRICESECONDOFTWOPART:
            return getPricesecondoftwopart();
        case PRICEFIRSTOFTWOPART:
            return getPricefirstoftwopart();
        case PRICEBUSINESSOFTWOPART:
            return getPricebusinessoftwopart();
        case TIMETHREEPLACE:
            return getTimethreeplace();
        case THREEPLACE:
            return getThreeplace();
        case PRICESECONDOFTHREEPART:
            return getPricesecondofthreepart();
        case PRICEFIRSTOFTHREEPART:
            return getPricefirstofthreepart();
        case PRICEBUSINESSOFTHREEPART:
            return getPricebusinessofthreepart();
        case TIMEFOREPLACE:
            return getTimeforeplace();
        case FOREPLACE:
            return getForeplace();
        case PRICESECONDOFFOREPART:
            return getPricesecondofforepart();
        case PRICEFIRSTOFFOREPART:
            return getPricefirstofforepart();
        case PRICEBUSINESSOFFOREPART:
            return getPricebusinessofforepart();
        case TIMEFIVEPLACE:
            return getTimefiveplace();
        case FIVEPLACE:
            return getFiveplace();
        case PRICESECONDOFFIVEPART:
            return getPricesecondoffivepart();
        case PRICEFIRSTOFFIVEPART:
            return getPricefirstoffivepart();
        case PRICEBUSINESSOFFIVEPART:
            return getPricebusinessoffivepart();
        case TIMESIXPLACE:
            return getTimesixplace();
        case SIXPLACE:
            return getSixplace();
        case ONESECONDCLASSSEAT:
            return getOnesecondclassseat();
        case TWOSECONDCLASSSEAT:
            return getTwosecondclassseat();
        case THREESECONDCLASSSEAT:
            return getThreesecondclassseat();
        case FORESECONDCLASSSEAT:
            return getForesecondclassseat();
        case FIVESECONDCLASSSEAT:
            return getFivesecondclassseat();
        case ONEFIRSTCLASSSEAT:
            return getOnefirstclassseat();
        case TWOFIRSTCLASSSEAT:
            return getTwofirstclassseat();
        case THREEFIRSTCLASSSEAT:
            return getThreefirstclassseat();
        case FOREFIRSTCLASSSEAT:
            return getForefirstclassseat();
        case FIVEFIRSTCLASSSEAT:
            return getFivefirstclassseat();
        case ONEBUSINESSCLASSSEAT:
            return getOnebusinessclassseat();
        case TWOBUSINESSCLASSSEAT:
            return getTwobusinessclassseat();
        case THREEBUSINESSCLASSSEAT:
            return getThreebusinessclassseat();
        case FOREBUSINESSCLASSSEAT:
            return getForebusinessclassseat();
        case FIVEBUSINESSCLASSSEAT:
            return getFivebusinessclassseat();
        case NUMBERCOLUMN:
            return getNumbercolumn();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDNUM:
            setIdnum((Number)value);
            return;
        case TRAINNAME:
            setTrainname((String)value);
            return;
        case TIMEONEPLACE:
            setTimeoneplace((Date)value);
            return;
        case ONEPLACE:
            setOneplace((String)value);
            return;
        case PRICESECONDOFONEPART:
            setPricesecondofonepart((Number)value);
            return;
        case PRICEFIRSTOFONEPART:
            setPricefirstofonepart((Number)value);
            return;
        case PRICEBUSINESSOFONEPART:
            setPricebusinessofonepart((Number)value);
            return;
        case TIMETWOPLACE:
            setTimetwoplace((Date)value);
            return;
        case TWOPLACE:
            setTwoplace((String)value);
            return;
        case PRICESECONDOFTWOPART:
            setPricesecondoftwopart((Number)value);
            return;
        case PRICEFIRSTOFTWOPART:
            setPricefirstoftwopart((Number)value);
            return;
        case PRICEBUSINESSOFTWOPART:
            setPricebusinessoftwopart((Number)value);
            return;
        case TIMETHREEPLACE:
            setTimethreeplace((Date)value);
            return;
        case THREEPLACE:
            setThreeplace((String)value);
            return;
        case PRICESECONDOFTHREEPART:
            setPricesecondofthreepart((Number)value);
            return;
        case PRICEFIRSTOFTHREEPART:
            setPricefirstofthreepart((Number)value);
            return;
        case PRICEBUSINESSOFTHREEPART:
            setPricebusinessofthreepart((Number)value);
            return;
        case TIMEFOREPLACE:
            setTimeforeplace((Date)value);
            return;
        case FOREPLACE:
            setForeplace((String)value);
            return;
        case PRICESECONDOFFOREPART:
            setPricesecondofforepart((Number)value);
            return;
        case PRICEFIRSTOFFOREPART:
            setPricefirstofforepart((Number)value);
            return;
        case PRICEBUSINESSOFFOREPART:
            setPricebusinessofforepart((Number)value);
            return;
        case TIMEFIVEPLACE:
            setTimefiveplace((Date)value);
            return;
        case FIVEPLACE:
            setFiveplace((String)value);
            return;
        case PRICESECONDOFFIVEPART:
            setPricesecondoffivepart((Number)value);
            return;
        case PRICEFIRSTOFFIVEPART:
            setPricefirstoffivepart((Number)value);
            return;
        case PRICEBUSINESSOFFIVEPART:
            setPricebusinessoffivepart((Number)value);
            return;
        case TIMESIXPLACE:
            setTimesixplace((Date)value);
            return;
        case SIXPLACE:
            setSixplace((String)value);
            return;
        case ONESECONDCLASSSEAT:
            setOnesecondclassseat((Number)value);
            return;
        case TWOSECONDCLASSSEAT:
            setTwosecondclassseat((Number)value);
            return;
        case THREESECONDCLASSSEAT:
            setThreesecondclassseat((Number)value);
            return;
        case FORESECONDCLASSSEAT:
            setForesecondclassseat((Number)value);
            return;
        case FIVESECONDCLASSSEAT:
            setFivesecondclassseat((Number)value);
            return;
        case ONEFIRSTCLASSSEAT:
            setOnefirstclassseat((Number)value);
            return;
        case TWOFIRSTCLASSSEAT:
            setTwofirstclassseat((Number)value);
            return;
        case THREEFIRSTCLASSSEAT:
            setThreefirstclassseat((Number)value);
            return;
        case FOREFIRSTCLASSSEAT:
            setForefirstclassseat((Number)value);
            return;
        case FIVEFIRSTCLASSSEAT:
            setFivefirstclassseat((Number)value);
            return;
        case ONEBUSINESSCLASSSEAT:
            setOnebusinessclassseat((Number)value);
            return;
        case TWOBUSINESSCLASSSEAT:
            setTwobusinessclassseat((Number)value);
            return;
        case THREEBUSINESSCLASSSEAT:
            setThreebusinessclassseat((Number)value);
            return;
        case FOREBUSINESSCLASSSEAT:
            setForebusinessclassseat((Number)value);
            return;
        case FIVEBUSINESSCLASSSEAT:
            setFivebusinessclassseat((Number)value);
            return;
        case NUMBERCOLUMN:
            setNumbercolumn((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number idnum) {
        return new Key(new Object[]{idnum});
    }
}
